/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SearchComponent {
        "data": [];
        "searchFunction": any;
        "searchPlaceholder": string;
    }
}
export interface SearchComponentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSearchComponentElement;
}
declare global {
    interface HTMLSearchComponentElement extends Components.SearchComponent, HTMLStencilElement {
    }
    var HTMLSearchComponentElement: {
        prototype: HTMLSearchComponentElement;
        new (): HTMLSearchComponentElement;
    };
    interface HTMLElementTagNameMap {
        "search-component": HTMLSearchComponentElement;
    }
}
declare namespace LocalJSX {
    interface SearchComponent {
        "data"?: [];
        "onChanged"?: (event: SearchComponentCustomEvent<any>) => void;
        "searchFunction"?: any;
        "searchPlaceholder"?: string;
    }
    interface IntrinsicElements {
        "search-component": SearchComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "search-component": LocalJSX.SearchComponent & JSXBase.HTMLAttributes<HTMLSearchComponentElement>;
        }
    }
}
